### ISSUE TITLE
The I/O operation has been aborted because of either a thread exit or an application request

### ISSUE THREAD

**Issue by e2gun** [m-expunged/guacamole-sharp#19]
When we closed browser executing RDP or SSH session, we got an error on debug mode that's "The I/O operation has been aborted because of either a thread exit or an application request". Thus, we think that this exception is caused in websocket. Is it true or false? if it is true how can we handle closing websocket or does it cause problems on release premise? Thanks for your help.

**Comment by m-expunged** [comment]
Are you using 1.0.0 or 2.1.0 (master branch)?

**Comment by m-expunged** [comment]
Played around with the 2.1.0 Version, can't replicate the exception for now. Can you post a snippet of the client side code, exception message etc.?

**Comment by ekremergun** [comment]
Thanks your answer. We tried sub code 
window.onunload = () => {
      client.disconnect();
};
but problem has not been solved yet. We still get these errors (guacamole-sharp file logs and visual studio 2022 exception code) 

![image](https://user-images.githubusercontent.com/15379304/199752087-36a44f3d-f259-41f0-8f3d-f337808ad416.png)
![image](https://user-images.githubusercontent.com/15379304/199752271-b6cc003f-eec4-4450-addb-0dc88145a478.png)

Thanks..
